site_description: APIJSON - The Progressive JavaScript Framework
google_analytics: UA-46852172-3
root_domain: cn.vuejs.org
vue_version: 2.6.10
platinum_sponsors_china:
  - url: 'http://www.dcloud.io/?hmsr=vuejsorg&hmpl=&hmcu=&hmkw=&hmci='
    img: dcloud.gif
video_sponsors_china:
  - url: http://cloud.youku.com/index.php?source=vuejs
    img: youku.png
special_sponsors:
  - url: 'https://stdlib.com/'
    img: stdlib.png
    description: 几分钟内在云端构建发布 API，免费试用。
platinum_sponsors:
  - url: 'http://www.transsion.com'
    img: 'www.transsion.com.jpeg'
    name: TRANSSION
  - url: 'http://shebaochina.com'
    img: 'shebaochina.com.png'
    name: 社保科技
  - url: 'http://www.8soo.com'
    img: 'www.8sso.com.jpeg'
    name: 八搜券
  - url: 'http://www.xxwolo.com'
    img: 'www.xxwolo.com.jpeg'
    name: 星星网络
  - url: 'http://www.aipaipai-inc.com'
    img: 'www.aipaipai-inc.com.png'
    name: 爱拍拍
  - url: 'https://www.shulian8.com'
    img: 'www.shulian8.com.png'
    name: 树联智能
  - url: 'http://www.hec-bang.com'
    img: 'www.hec-bang.com.png'
    name: 华张科技
  - url: 'http://www.xmfish.com'
    img: 'www.xmfish.com.gif'
    name: 厦门小鱼
  - url: 'http://juting.vip'
    img: 'juting.vip.png'
    name: 聚听有声
gold_sponsors:
  - url: 'https://github.com/TommyLemon'
    img: 'https://avatars1.githubusercontent.com/u/5738175?s=400&u=5b2f372f0c03fae8f249d2d754e38971c2e17b92&v=4'
    name: Contributer
  - url: 'https://github.com/TommyLemon/APIJSON/pull/41'
    img: 'https://avatars0.githubusercontent.com/u/39320217?s=460&v=4'
    name: Contributer
  - url: 'https://github.com/TommyLemon/APIJSON/pull/43'
    img: 'https://avatars0.githubusercontent.com/u/23173448?s=460&v=4'
    name: Contributer
  - url: 'https://github.com/TommyLemon/APIJSON/pull/47'
    img: 'https://avatars2.githubusercontent.com/u/31512287?s=400&v=4'
    name: Contributer
  - url: 'https://github.com/TommyLemon/APIJSON/pull/70'
    img: 'https://avatars1.githubusercontent.com/u/22228201?s=400&v=4'
    name: Contributer
  - url: 'https://github.com/TommyLemon/APIJSON/pull/74'
    img: 'https://avatars0.githubusercontent.com/u/1274536?s=400&v=4'
    name: Contributer
  - url: 'https://github.com/APIJSON/APIJSON/pull/92'
    img: 'https://avatars3.githubusercontent.com/u/6327228?s=400&v=4'
    name: Contributer
  - url: 'https://github.com/TommyLemon/APIJSON/pull/69'
    img: 'https://avatars0.githubusercontent.com/u/13880474?s=400&v=4'
    name: Contributer
  - url: 'https://github.com/TommyLemon/APIJSON/pull/72'
    img: 'https://avatars1.githubusercontent.com/u/10663804?s=400&v=4'
    name: Contributer
  - url: 'https://github.com/TommyLemon/APIJSON/pull/33'
    img: 'https://avatars1.githubusercontent.com/u/5328313?s=460&v=4'
    name: Contributer
silver_sponsors:
  - url: 'https://github.com/liaozb/APIJSON.NET'
    img: 'https://avatars3.githubusercontent.com/u/12622501?s=400&v=4'
    name: Author
  - url: 'https://github.com/qq547057827/apijson-php'
    img: 'https://avatars3.githubusercontent.com/u/1657532?s=400&v=4'
    name: Author
  - url: 'https://github.com/TEsTsLA/apijson'
    img: 'https://avatars2.githubusercontent.com/u/17310639?s=400&v=4'
    name: Author
  - url: 'https://github.com/zhangchunlin/uliweb-apijson'
    img: 'https://avatars0.githubusercontent.com/u/359281?s=400&v=4'
    name: Author
  - url: 'https://github.com/crazytaxi824/APIJSON'
    img: 'https://avatars3.githubusercontent.com/u/16500384?s=400&v=4'
    name: Author
  - url: 'https://github.com/luckyxiaomo/APIJSONKOTLIN'
    img: 'https://avatars2.githubusercontent.com/u/42728605?s=400&v=4'
    name: Author
  - url: 'https://github.com/Zerounary/APIJSONParser'
    img: 'https://avatars2.githubusercontent.com/u/31512287?s=400&v=4'
    name: Author
  - url: 'https://gitee.com/zhiyuexin/ApiJsonByJFinal'
    img: 'https://avatar.gitee.com/uploads/90/490_zhiyuexin.jpg!avatar100?1368664499'
    name: Author
  - url: 'https://github.com/Airforce-1/SpringServer1.2-APIJSON'
    img: 'https://avatars3.githubusercontent.com/u/6212428?s=400&v=4'
    name: Author
  - url: 'https://github.com/vincentCheng/apijson-doc'
    img: 'https://avatars3.githubusercontent.com/u/6327228?s=400&v=4'
    name: Author
bronze_sponsors:
  - url: 'http://tighten.co/'
    img: tighten_co.png
    name: Tighten.co
  - url: 'https://www.accelebrate.com/'
    img: accelebrate.png
    name: Accelebrate
  - url: 'https://polyglotengineer.com/derek.pollard'
    img: derek_pollard.png
    name: Derek Pollard
  - url: 'https://www.earthlink.ro'
    img: earthlink.png
    name: Earthlink
