site_description: APIJSON - The Progressive JavaScript Framework
google_analytics: UA-46852172-3
root_domain: cn.vuejs.org
vue_version: 2.6.10
platinum_sponsors_china:
  - url: 'http://www.dcloud.io/?hmsr=vuejsorg&hmpl=&hmcu=&hmkw=&hmci='
    img: dcloud.gif
video_sponsors_china:
  - url: http://cloud.youku.com/index.php?source=vuejs
    img: youku.png
special_sponsors:
  - url: 'https://stdlib.com/'
    img: stdlib.png
    description: 几分钟内在云端构建发布 API，免费试用。
platinum_sponsors:
  - url: 'http://www.transsion.com'
    img: 'http://www.transsion.com/static/images/logo.jpg'
    name: TRANSSION
  - url: 'http://shebaochina.com'
    img: 'http://shebaochina.com/static/cn/img/index/logo.png'
    name: 社保科技
  - url: 'http://www.8soo.com'
    img: 'http://ww1.sinaimg.cn/large/756dd729gw1f9n5ckuq6vj208902it8v.jpg'
    name: 八搜券
  - url: 'http://www.xxwolo.com'
    img: 'http://img.qichacha.com/Product/a917fcca-fbb1-44a2-a079-56985ebf8f9c.jpg'
    name: 星星网络
  - url: 'http://www.aipaipai-inc.com'
    img: 'http://www.aipaipai-inc.com/uploadfile/upload/2019042913403029.png'
    name: 爱拍拍
  - url: 'https://www.shulian8.com'
    img: 'https://bookstore-prod.oss-cn-hangzhou.aliyuncs.com/%E5%90%8E%E5%8F%B0%E9%A1%B5%E9%9D%A2_03.png'
    name: 树联智能
  - url: 'http://www.hec-bang.com'
    img: 'http://www.hec-bang.com/assets/images/logo-200x50.png'
    name: 华张科技
  - url: 'http://www.xmfish.com'
    img: 'http://www.xmfish.com/images/chanel/www/f_logo.gif'
    name: 厦门小鱼
  - url: 'http://juting.vip'
    img: 'http://i.juting.vip/wp-file/2018/12/logo1-1.png'
    name: 聚听有声
gold_sponsors:
  - url: 'https://www.vuemastery.com/'
    img: vuemastery.png
    name: VueMastery
  - url: 'https://laravel.com'
    img: laravel.png
    name: Laravel
  - url: 'https://chaitin.cn/en/'
    img: chaitin.png
    name: Chaitin
  - url: 'https://htmlburger.com'
    img: html_burger.png
    name: HTML Burger
  - url: 'https://www.frontenddeveloperlove.com/'
    img: frontend_love.png
    name: Frontend Love
  - url: 'https://onsen.io/vue/'
    img: onsen_ui.png
    name: Onsen UI
  - url: 'https://neds.com.au/'
    img: neds.png
    name: Neds
  - url: 'https://icons8.com/'
    img: icons_8.png
    name: Icons 8
  - url: 'https://vuejobs.com/?ref=vuejs'
    img: vuejobs.png
    name: VueJobs
  - url: 'https://www.valuecoders.com'
    img: valuecoders.png
    name: ValueCoders
  - url: 'https://tidelift.com/subscription/npm/vue'
    img: tidelift.png
    name: Tidelift
  - url: >-
      http://www.syncfusion.com/?utm_source=vuejs&utm_medium=list&utm_campaign=vuejsjslistcy19
    img: syncfusion.png
    name: SyncFusion
  - url: 'https://opteo.com/vue'
    img: opteo.png
    name: Opteo
  - url: 'https://devsquad.com/'
    img: devsquad.png
    name: DevSquad
  - url: 'https://www.firesticktricks.com/'
    img: firestick_tricks.png
    name: Firestick Tricks
  - url: 'https://intygrate.com/'
    img: intygrate.png
    name: Intygrate
  - url: 'https://isleofcode.com/'
    img: isle_of_code.png
    name: Isle of Code
  - url: 'https://passionatepeople.io/'
    img: passionate_people.png
    name: Passionate People
  - url: 'http://en.shopware.com/'
    img: shopware_ag.png
    name: shopware AG
  - url: >-
      https://x-team.com/join/?utm_source=vuejsorg&utm_medium=sponsor&utm_campaign=vuejsorg-patreon
    img: x_team.png
    name: X-Team
  - url: 'https://www.vpnranks.com/'
    img: vpnranks.png
    name: VPNRanks
  - url: 'https://www.simplyswitch.com/'
    img: energy_comparison.png
    name: Energy Comparison
  - url: 'https://www.bacancytechnology.com'
    img: bacancy_technology.png
    name: Bacancy Technology
  - url: 'https://blokt.com/'
    img: blokt_cryptocurrency_news.png
    name: Blokt Cryptocurrency News
  - url: 'https://www.jqwidgets.com/vue/'
    img: jqwidgets_ltd.png
    name: jQWidgets LTD
  - url: 'https://www.y8.com/'
    img: y8.png
    name: Y8
silver_sponsors:
  - url: 'https://dopamine.bg/'
    img: dopamine.png
    name: Dopamine
bronze_sponsors:
  - url: 'http://tighten.co/'
    img: tighten_co.png
    name: Tighten.co
  - url: 'https://www.accelebrate.com/'
    img: accelebrate.png
    name: Accelebrate
  - url: 'https://polyglotengineer.com/derek.pollard'
    img: derek_pollard.png
    name: Derek Pollard
  - url: 'https://www.earthlink.ro'
    img: earthlink.png
    name: Earthlink
